name: Python Application CI

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨0点触发
  workflow_dispatch:

env:
  GITHUB_USER_NAME: carlosfuego # your github id
  GITHUB_USER_EMAIL: huanyang2022@gmail.com # your email address

jobs:
  build:

    runs-on: ubuntu-latest  # 运行环境

    steps:
    - name: Check out repository
      uses: actions/checkout@v3  # 检出代码仓库

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # 设置Python版本为3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run main.py 
      run: |
        python main.py search --keyword "kv cache" --max_results 10 --output_dir saves/
        ls saves/

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "${{ env.GITHUB_USER_NAME }}"
        git config --global user.email "${{ env.GITHUB_USER_EMAIL }}"
        git add .
        git diff --quiet && echo "No changes to commit" && exit 0
        git commit -m "Automatic update from GitHub Actions" || true
        git push origin HEAD:main
