name: Python Application CI

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨0点触发
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest  # 运行环境

    steps:
    - name: Check out repository
      uses: actions/checkout@v2  # 检出代码仓库

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # 设置Python版本为3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run main.py 
      run: python main.py search --keyword "kv cache" --max_results 10 --output_dir saves  # 运行main.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USER_NAME: ${{ secrets.USER_NAME }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
      run: |
        git add .
        git diff --quiet && echo "No changes to commit" && exit 0
        git commit -m "Automatic update from GitHub Actions" || exit 0
        git push origin HEAD:main